# rootDirectory for indices, empty value defaults to user directory, uncomment line below to override
#rootDirectory: '/home/zbyszko'
# subdirectory containing Lucene indices
luceneDirectory: 'Lucene'
# subdirectories for each index used in examples and exercises
indexDirectories:
  KEYWORD_TOKENIZER_EXAMPLE: 'keyword_tokenizer'
  FACETING_EXAMPLE: 'faceting'
  WHITESPACE_TOKENIZER_EXAMPLE: 'whitespace_tokenizer'
  STANDARD_TOKENIZER_EXAMPLE: 'standard_tokenizer'
  LOWER_CASE_TOKEN_FILTER_EXAMPLE: 'lower_case_token_filter'
  STOP_WORDS_TOKEN_FILTER_EXAMPLE: 'stop_words_token_filter'
  SYNONYM_GRAPH_FILTER_EXAMPLE: 'synonym_graph_filter'
  POLISH_ANALYZER_EXAMPLE: "polish_analyzer_example"
  HTML_CHAR_STRIP_FILTER_EXAMPLE: 'html_char_strip_filter'
  WIKIPEDIA_SEARCH: 'wikipedia'

