package com.wilqor.workshop.bytebay.lucene.config;

public enum IndexType {
    KEYWORD_ANALYZER_EXAMPLE,
    FACETING_EXAMPLE,
    WHITESPACE_ANALYZER_EXAMPLE,
    STANDARD_ANALYZER_EXAMPLE,
    LOWER_CASE_TOKEN_FILTER_EXAMPLE,
    STOP_WORDS_TOKEN_FILTER_EXAMPLE
}
