package com.wilqor.workshop.bytebay.lucene.config;

public enum IndexType {
    KEYWORD_TOKENIZER_EXAMPLE,
    FACETING_EXAMPLE,
    WHITESPACE_TOKENIZER_EXAMPLE,
    STANDARD_TOKENIZER_EXAMPLE,
    LOWER_CASE_TOKEN_FILTER_EXAMPLE,
    STOP_WORDS_TOKEN_FILTER_EXAMPLE,
    SYNONYM_TOKEN_FILTER_EXAMPLE,
    HTML_CHAR_STRIP_FILTER_EXAMPLE,
    WIKIPEDIA_SEARCH
}
